/**
 * Enterprise Invoice Types
 *
 * These types represent the immutable invoice data that is captured at order
 * creation and embedded directly into the Order document. Once written, these
 * values MUST NEVER change — they form the legal record of the transaction.
 */

// ─── Invoice Metadata ────────────────────────────────────────────────────────

export interface IOrderInvoice {
  /** Sequential invoice number, e.g. INV-2026-000001 */
  number: string;
  /** The date the invoice was formally issued */
  issuedAt: Date;
  /** Timestamp when the snapshot was generated by the system */
  generatedAt: Date;
  /** True if this invoice was backfilled by a migration script (not generated at checkout) */
  migrationGenerated?: boolean;
}

// ─── Store Snapshot ──────────────────────────────────────────────────────────

export interface IOrderStoreSnapshot {
  /** Brand / display name shown on the invoice header */
  displayName: string;
  /** Registered legal entity name (required for GST invoices) */
  legalCompanyName: string;
  /** Logo URL at the time of order */
  logo?: string;
  /** GSTIN for tax compliance */
  gstin: string;
  /** Structured address */
  addressLine1: string;
  addressLine2?: string;
  city: string;
  state: string;
  country: string;
  postalCode: string;
  /** Contact info */
  email: string;
  phone: string;
}

// ─── Tax Snapshot ────────────────────────────────────────────────────────────

export interface IOrderTaxSnapshot {
  /** Order subtotal before discount */
  subtotal: number;
  /** Discount amount applied */
  discount: number;
  /** Taxable amount (subtotal - discount, or base if tax-inclusive) */
  taxableAmount: number;
  /** Central GST component */
  cgst: number;
  /** State GST component */
  sgst: number;
  /** Integrated GST (for inter-state, 0 for intra-state) */
  igst: number;
  /** Total tax = cgst + sgst + igst */
  totalTax: number;
  /** Grand total charged to the customer */
  grandTotal: number;
  /** ISO 4217 currency code */
  currency: string;
  /** Currency display symbol */
  currencySymbol: string;
}

// ─── Full Invoice DTO (returned to frontend) ─────────────────────────────────

export interface IInvoiceDTO {
  orderId: string;
  invoice: IOrderInvoice;
  store: IOrderStoreSnapshot;
  tax: IOrderTaxSnapshot;

  // These are read directly from the live Order document (not snapshotted):
  paymentMethod: string;
  paymentStatus: string;
  razorpayPaymentId?: string;

  // Shipping is live (not snapshotted):
  courierPartner?: string;
  trackingNumber?: string;
  dispatchDate?: Date;

  // Customer & items come from the Order itself:
  shippingAddress: any;
  items: any[];
  shippingFee: number;
  couponCode?: string;

  createdAt: Date;
}
