export class VideoHandler {
  /**
   * Eager transformations for videos (thumbnails and posters)
   * These are generated by Cloudinary *after* the initial upload finishes.
   */
  static getEagerTransforms() {
    return [
      { width: 800, crop: 'limit', format: 'webp', start_offset: 'auto', type: 'poster' }, // Poster image
      { width: 400, crop: 'limit', format: 'webp', start_offset: 'auto', type: 'thumbnail' }, // Small thumbnail
    ];
  }

  static extractEagerUrls(result: any): { posterUrl?: string; thumbnailUrl?: string } {
    if (!result || !result.secure_url) return {};

    // Asynchronous eager transforms might not be ready immediately in result.eager.
    // Programmatically construct the URLs using Cloudinary URL syntax.
    const urlParts = result.secure_url.split('/upload/');
    if (urlParts.length !== 2) return {};

    // Strip the video extension (e.g., .mp4, .mov)
    const basePath = urlParts[1].replace(/\.[^/.]+$/, '');

    const posterUrl = `${urlParts[0]}/upload/w_800,c_limit,f_webp,so_auto/${basePath}.webp`;
    const thumbnailUrl = `${urlParts[0]}/upload/w_400,c_limit,f_webp,so_auto/${basePath}.webp`;

    return { posterUrl, thumbnailUrl };
  }
}
