import {
  PURCHASE_STATUS,
  RENTAL_STATUS,
  EVENT_STATUS,
  CUSTOM_ORDER_STATUS,
  TRANSACTION_TYPES,
} from '../constants/statusConstants';
import logger from '../config/logger';

export class TransitionValidationService {
  /**
   * Defines allowed status transitions for Purchase Orders
   */
  private static getPurchaseTransitions(): Record<string, string[]> {
    return {
      [PURCHASE_STATUS.PENDING]: [
        PURCHASE_STATUS.PENDING_APPROVAL,
        PURCHASE_STATUS.CONFIRMED,
        PURCHASE_STATUS.CANCELLED,
      ],
      [PURCHASE_STATUS.PENDING_APPROVAL]: [PURCHASE_STATUS.CONFIRMED, PURCHASE_STATUS.CANCELLED],
      [PURCHASE_STATUS.CONFIRMED]: [PURCHASE_STATUS.PROCESSING, PURCHASE_STATUS.CANCELLED],
      [PURCHASE_STATUS.PROCESSING]: [PURCHASE_STATUS.DELIVERED, PURCHASE_STATUS.CANCELLED],
      [PURCHASE_STATUS.DELIVERED]: [PURCHASE_STATUS.RETURN_REQUESTED],
      [PURCHASE_STATUS.CANCELLED]: [PURCHASE_STATUS.REFUNDED],
      [PURCHASE_STATUS.RETURN_REQUESTED]: [
        PURCHASE_STATUS.RETURN_APPROVED,
        PURCHASE_STATUS.CANCELLED,
      ], // cancelled means return denied
      [PURCHASE_STATUS.RETURN_APPROVED]: [PURCHASE_STATUS.RETURNED],
      [PURCHASE_STATUS.RETURNED]: [PURCHASE_STATUS.REFUNDED],
      [PURCHASE_STATUS.REFUNDED]: [],
      [PURCHASE_STATUS.UNKNOWN]: [],
    };
  }

  /**
   * Defines allowed status transitions for Rental Orders
   */
  private static getRentalTransitions(): Record<string, string[]> {
    return {
      [RENTAL_STATUS.PENDING_PAYMENT]: [
        RENTAL_STATUS.PENDING_APPROVAL,
        RENTAL_STATUS.CONFIRMED,
        RENTAL_STATUS.CANCELLED,
      ],
      [RENTAL_STATUS.PENDING_APPROVAL]: [RENTAL_STATUS.CONFIRMED, RENTAL_STATUS.CANCELLED],
      [RENTAL_STATUS.CONFIRMED]: [
        RENTAL_STATUS.PREPARING,
        RENTAL_STATUS.PACKED,
        RENTAL_STATUS.CANCELLED,
      ],
      [RENTAL_STATUS.PREPARING]: [RENTAL_STATUS.PACKED, RENTAL_STATUS.CANCELLED],
      [RENTAL_STATUS.PACKED]: [RENTAL_STATUS.DISPATCHED, RENTAL_STATUS.CANCELLED],
      [RENTAL_STATUS.DISPATCHED]: [RENTAL_STATUS.DELIVERED],
      [RENTAL_STATUS.DELIVERED]: [RENTAL_STATUS.RENTAL_ACTIVE, RENTAL_STATUS.RETURN_INITIATED],
      [RENTAL_STATUS.RENTAL_ACTIVE]: [
        RENTAL_STATUS.RETURN_DUE,
        RENTAL_STATUS.RETURN_INITIATED,
        RENTAL_STATUS.OVERDUE,
      ],
      [RENTAL_STATUS.RETURN_DUE]: [RENTAL_STATUS.RETURN_INITIATED, RENTAL_STATUS.OVERDUE],
      [RENTAL_STATUS.RETURN_INITIATED]: [
        RENTAL_STATUS.RETURN_IN_TRANSIT,
        RENTAL_STATUS.RETURN_RECEIVED,
      ],
      [RENTAL_STATUS.RETURN_IN_TRANSIT]: [RENTAL_STATUS.RETURN_RECEIVED],
      [RENTAL_STATUS.RETURN_RECEIVED]: [RENTAL_STATUS.INSPECTION_PENDING],
      [RENTAL_STATUS.INSPECTION_PENDING]: [RENTAL_STATUS.INSPECTED, RENTAL_STATUS.DAMAGED],
      [RENTAL_STATUS.INSPECTED]: [RENTAL_STATUS.DEPOSIT_REFUND_PENDING, RENTAL_STATUS.COMPLETED],
      [RENTAL_STATUS.DEPOSIT_REFUND_PENDING]: [RENTAL_STATUS.COMPLETED],
      [RENTAL_STATUS.OVERDUE]: [RENTAL_STATUS.RETURN_INITIATED, RENTAL_STATUS.RETURN_RECEIVED],
      [RENTAL_STATUS.DAMAGED]: [RENTAL_STATUS.DEPOSIT_REFUND_PENDING, RENTAL_STATUS.COMPLETED],
      [RENTAL_STATUS.CANCELLED]: [],
      [RENTAL_STATUS.COMPLETED]: [],
      [RENTAL_STATUS.UNKNOWN]: [],
    };
  }

  /**
   * Defines allowed status transitions for Event Bookings
   */
  private static getEventTransitions(): Record<string, string[]> {
    return {
      [EVENT_STATUS.INQUIRY]: [EVENT_STATUS.QUOTE_SENT, EVENT_STATUS.CANCELLED],
      [EVENT_STATUS.QUOTE_SENT]: [EVENT_STATUS.PAYMENT_PENDING, EVENT_STATUS.CANCELLED],
      [EVENT_STATUS.PAYMENT_PENDING]: [
        EVENT_STATUS.ADVANCE_PAID,
        EVENT_STATUS.CONFIRMED,
        EVENT_STATUS.CANCELLED,
      ],
      [EVENT_STATUS.ADVANCE_PAID]: [EVENT_STATUS.CONFIRMED, EVENT_STATUS.CANCELLED],
      [EVENT_STATUS.CONFIRMED]: [
        EVENT_STATUS.PLANNING,
        EVENT_STATUS.TEAM_ASSIGNED,
        EVENT_STATUS.CANCELLED,
      ],
      [EVENT_STATUS.PLANNING]: [
        EVENT_STATUS.TEAM_ASSIGNED,
        EVENT_STATUS.PREPARATION,
        EVENT_STATUS.CANCELLED,
      ],
      [EVENT_STATUS.TEAM_ASSIGNED]: [EVENT_STATUS.PREPARATION, EVENT_STATUS.CANCELLED],
      [EVENT_STATUS.PREPARATION]: [EVENT_STATUS.DISPATCHED_TO_VENUE, EVENT_STATUS.CANCELLED],
      [EVENT_STATUS.DISPATCHED_TO_VENUE]: [EVENT_STATUS.SETUP_IN_PROGRESS],
      [EVENT_STATUS.SETUP_IN_PROGRESS]: [EVENT_STATUS.SETUP_COMPLETED],
      [EVENT_STATUS.SETUP_COMPLETED]: [EVENT_STATUS.EVENT_IN_PROGRESS],
      [EVENT_STATUS.EVENT_IN_PROGRESS]: [EVENT_STATUS.EVENT_COMPLETED],
      [EVENT_STATUS.EVENT_COMPLETED]: [EVENT_STATUS.TEARDOWN],
      [EVENT_STATUS.TEARDOWN]: [EVENT_STATUS.RETURNING_TO_WAREHOUSE],
      [EVENT_STATUS.RETURNING_TO_WAREHOUSE]: [
        EVENT_STATUS.FINAL_SETTLEMENT,
        EVENT_STATUS.COMPLETED,
      ],
      [EVENT_STATUS.FINAL_SETTLEMENT]: [EVENT_STATUS.COMPLETED],
      [EVENT_STATUS.COMPLETED]: [],
      [EVENT_STATUS.CANCELLED]: [],
      [EVENT_STATUS.UNKNOWN]: [],
    };
  }

  /**
   * Defines allowed status transitions for Custom Orders
   */
  private static getCustomOrderTransitions(): Record<string, string[]> {
    return {
      [CUSTOM_ORDER_STATUS.REQUEST_SUBMITTED]: [
        CUSTOM_ORDER_STATUS.UNDER_REVIEW,
        CUSTOM_ORDER_STATUS.CANCELLED,
      ],
      [CUSTOM_ORDER_STATUS.UNDER_REVIEW]: [
        CUSTOM_ORDER_STATUS.QUOTE_SENT,
        CUSTOM_ORDER_STATUS.CANCELLED,
      ],
      [CUSTOM_ORDER_STATUS.QUOTE_SENT]: [
        CUSTOM_ORDER_STATUS.CUSTOMER_APPROVAL_PENDING,
        CUSTOM_ORDER_STATUS.CANCELLED,
      ],
      [CUSTOM_ORDER_STATUS.CUSTOMER_APPROVAL_PENDING]: [
        CUSTOM_ORDER_STATUS.PAYMENT_PENDING,
        CUSTOM_ORDER_STATUS.REWORK_REQUIRED,
        CUSTOM_ORDER_STATUS.CANCELLED,
      ],
      [CUSTOM_ORDER_STATUS.REWORK_REQUIRED]: [
        CUSTOM_ORDER_STATUS.UNDER_REVIEW,
        CUSTOM_ORDER_STATUS.QUOTE_SENT,
        CUSTOM_ORDER_STATUS.CANCELLED,
      ],
      [CUSTOM_ORDER_STATUS.PAYMENT_PENDING]: [
        CUSTOM_ORDER_STATUS.PAYMENT_CONFIRMED,
        CUSTOM_ORDER_STATUS.CANCELLED,
      ],
      [CUSTOM_ORDER_STATUS.PAYMENT_CONFIRMED]: [
        CUSTOM_ORDER_STATUS.DESIGN_IN_PROGRESS,
        CUSTOM_ORDER_STATUS.IN_PRODUCTION,
        CUSTOM_ORDER_STATUS.CANCELLED,
      ],
      [CUSTOM_ORDER_STATUS.DESIGN_IN_PROGRESS]: [
        CUSTOM_ORDER_STATUS.CUSTOMER_DESIGN_APPROVAL,
        CUSTOM_ORDER_STATUS.IN_PRODUCTION,
        CUSTOM_ORDER_STATUS.CANCELLED,
      ],
      [CUSTOM_ORDER_STATUS.CUSTOMER_DESIGN_APPROVAL]: [
        CUSTOM_ORDER_STATUS.IN_PRODUCTION,
        CUSTOM_ORDER_STATUS.REWORK_REQUIRED,
        CUSTOM_ORDER_STATUS.CANCELLED,
      ],
      [CUSTOM_ORDER_STATUS.IN_PRODUCTION]: [
        CUSTOM_ORDER_STATUS.QUALITY_CHECK,
        CUSTOM_ORDER_STATUS.CANCELLED,
      ],
      [CUSTOM_ORDER_STATUS.QUALITY_CHECK]: [
        CUSTOM_ORDER_STATUS.PACKED,
        CUSTOM_ORDER_STATUS.REWORK_REQUIRED,
        CUSTOM_ORDER_STATUS.CANCELLED,
      ],
      [CUSTOM_ORDER_STATUS.PACKED]: [CUSTOM_ORDER_STATUS.DISPATCHED, CUSTOM_ORDER_STATUS.CANCELLED],
      [CUSTOM_ORDER_STATUS.DISPATCHED]: [CUSTOM_ORDER_STATUS.DELIVERED],
      [CUSTOM_ORDER_STATUS.DELIVERED]: [CUSTOM_ORDER_STATUS.COMPLETED],
      [CUSTOM_ORDER_STATUS.COMPLETED]: [],
      [CUSTOM_ORDER_STATUS.CANCELLED]: [],
      [CUSTOM_ORDER_STATUS.UNKNOWN]: [],
    };
  }

  /**
   * Validates if a transition from currentStatus to newStatus is allowed.
   */
  static validateTransition(
    transactionType: string,
    currentStatus: string,
    newStatus: string,
  ): boolean {
    if (currentStatus === newStatus) return true; // Idempotent

    let transitions: Record<string, string[]>;

    switch (transactionType) {
      case TRANSACTION_TYPES.PURCHASE:
        transitions = this.getPurchaseTransitions();
        break;
      case TRANSACTION_TYPES.RENTAL:
        transitions = this.getRentalTransitions();
        break;
      case TRANSACTION_TYPES.EVENT_BOOKING:
        transitions = this.getEventTransitions();
        break;
      case TRANSACTION_TYPES.CUSTOM_ORDER:
        transitions = this.getCustomOrderTransitions();
        break;
      default:
        logger.error(`Unknown transaction type in validation: ${transactionType}`);
        return false;
    }

    const allowed = transitions[currentStatus] || [];
    return allowed.includes(newStatus);
  }

  /**
   * Returns all allowed next states for a given status
   */
  static getAllowedTransitions(transactionType: string, currentStatus: string): string[] {
    switch (transactionType) {
      case TRANSACTION_TYPES.PURCHASE:
        return this.getPurchaseTransitions()[currentStatus] || [];
      case TRANSACTION_TYPES.RENTAL:
        return this.getRentalTransitions()[currentStatus] || [];
      case TRANSACTION_TYPES.EVENT_BOOKING:
        return this.getEventTransitions()[currentStatus] || [];
      case TRANSACTION_TYPES.CUSTOM_ORDER:
        return this.getCustomOrderTransitions()[currentStatus] || [];
      default:
        return [];
    }
  }
}
