export const navSections = [
  {
    label: 'Dashboard',
    items: [
      {
        label: 'Dashboard',
        icon: 'dashboard',
        path: '/admin',
        keywords: 'stats, home, sales, overview',
        domain: 'revenue',
      },
      {
        label: 'Executive Summary',
        icon: 'trending_up',
        path: '/admin/executive',
        keywords: 'ceo, owner, top level, summary, high level',
        domain: 'revenue',
      },
    ],
  },
  {
    label: 'Website Management',
    items: [
      {
        label: 'Dynamic Layouts',
        icon: 'view_carousel',
        path: '/admin/layouts',
        keywords: 'layouts, sections, homepage',
        domain: 'settings',
      },
      {
        label: 'Edit Web Pages',
        icon: 'edit_note',
        path: '/admin/homepage',
        keywords: 'cms, homepage, hero, pages, policy',
        domain: 'settings',
      },
      {
        label: 'Photo Gallery',
        icon: 'photo_library',
        path: '/admin/gallery',
        keywords: 'photos, heritage, images',
        domain: 'settings',
      },
      {
        label: 'Draft Manager',
        icon: 'draft',
        path: '/admin/drafts',
        keywords: 'drafts, auto-save, unsaved, offline',
        domain: 'settings',
      },
      {
        label: 'Policy Management',
        icon: 'gavel',
        path: '/admin/policies',
        keywords: 'policy, terms, legal, privacy',
        domain: 'settings',
      },
      {
        label: 'View Storefront',
        icon: 'open_in_new',
        path: '/',
        keywords: 'storefront, live, view, public',
        domain: 'settings',
      },
    ],
  },
  {
    label: 'Catalog Management',
    items: [
      {
        label: 'Product List',
        icon: 'inventory_2',
        path: '/admin/products',
        keywords: 'items, stock, catalog',
        domain: 'products',
      },
      {
        label: 'Categories',
        icon: 'category',
        path: '/admin/categories',
        keywords: 'taxonomy, tags, labels',
        domain: 'products',
      },
      {
        label: 'Stock Levels',
        icon: 'warehouse',
        path: '/admin/inventory',
        keywords: 'alerts, stock count, storage',
        domain: 'products',
      },
      {
        label: 'Visual Search',
        icon: 'lens_blur',
        path: '/admin/visual-search',
        keywords: 'ai, lens, vision, image search',
        domain: 'settings',
      },
    ],
  },
  {
    label: 'Bookings',
    items: [
      {
        label: 'Event Bookings',
        icon: 'event',
        path: '/admin/events',
        keywords: 'booking, setups, dates',
        domain: 'orders',
      },
      {
        label: 'Rental Calendar',
        icon: 'calendar_month',
        path: '/admin/rental-calendar',
        keywords: 'schedule, availability, tracking',
        domain: 'orders',
      },
    ],
  },
  {
    label: 'Orders',
    items: [
      {
        label: 'Purchase Orders',
        icon: 'shopping_bag',
        path: '/admin/orders',
        keywords: 'sales, checkout, delivery',
        domain: 'orders',
      },
      {
        label: 'Rental Orders',
        icon: 'car_rental',
        path: '/admin/rentals',
        keywords: 'rentals, leases, returns',
        domain: 'orders',
      },
      {
        label: 'Custom Orders',
        icon: 'architecture',
        path: '/admin/custom-orders',
        keywords: 'customization, consultation, bespoke, custom orders',
        domain: 'orders',
      },
      {
        label: 'Payments',
        icon: 'payments',
        path: '/admin/payments',
        keywords: 'razorpay, cod, invoice, cashflow',
        domain: 'revenue',
      },
    ],
  },
  {
    label: 'Returns & Refunds',
    items: [
      {
        label: 'Return Dashboard',
        icon: 'assignment_return',
        path: '/admin/returns',
        keywords: 'returns, refunds, exchanges, dashboard',
        domain: 'orders',
      },
      {
        label: 'Return Requests',
        icon: 'undo',
        path: '/admin/returns/requests',
        keywords: 'return requests, pending, approved',
        domain: 'orders',
      },
      {
        label: 'Exchange Requests',
        icon: 'swap_horiz',
        path: '/admin/returns/exchanges',
        keywords: 'exchange, swap, replacement',
        domain: 'orders',
      },
      {
        label: 'Refund Requests',
        icon: 'account_balance_wallet',
        path: '/admin/returns/refunds',
        keywords: 'refunds, payments, gateway',
        domain: 'revenue',
      },
      {
        label: 'Pickup Management',
        icon: 'local_shipping',
        path: '/admin/returns/pickups',
        keywords: 'pickup, logistics, driver, courier',
        domain: 'orders',
      },
      {
        label: 'Return Analytics',
        icon: 'trending_down',
        path: '/admin/returns/analytics',
        keywords: 'trends, reports, revenue impact',
        domain: 'revenue',
      },
      {
        label: 'Fraud Detection',
        icon: 'shield',
        path: '/admin/returns/fraud',
        keywords: 'fraud, abuse, risk, suspicious',
        domain: 'danger',
      },
      {
        label: 'Return Settings',
        icon: 'tune',
        path: '/admin/returns/settings',
        keywords: 'policy, window, rules, configuration',
        domain: 'settings',
      },
    ],
  },
  {
    label: 'Customers',
    items: [
      {
        label: 'Customers',
        icon: 'group',
        path: '/admin/customers',
        keywords: 'users, crm, segments, vip',
        domain: 'users',
      },
      {
        label: 'Customer Intelligence',
        icon: 'insights',
        path: '/admin/customers/intelligence',
        keywords: '360, insights, analytics, segments',
        domain: 'users',
      },
    ],
  },
  {
    label: 'Marketing & Sales',
    items: [
      {
        label: 'Discount Coupons',
        icon: 'sell',
        path: '/admin/coupons',
        keywords: 'discounts, vouchers',
        domain: 'revenue',
      },
      {
        label: 'Marketing Emails',
        icon: 'campaign',
        path: '/admin/campaigns',
        keywords: 'marketing, email, newsletters',
        domain: 'revenue',
      },
    ],
  },
  {
    label: 'Analytics',
    items: [
      {
        label: 'Sales Reports',
        icon: 'query_stats',
        path: '/admin/analytics',
        keywords: 'trends, metrics, profits',
        domain: 'revenue',
      },
      {
        label: 'AI Engine Analytics',
        icon: 'psychology',
        path: '/admin/recommendations',
        keywords: 'recommendations, trending, metrics',
        domain: 'settings',
      },
    ],
  },
  {
    label: 'Administration',
    items: [
      {
        label: 'Manage Staff',
        icon: 'groups',
        path: '/admin/team',
        keywords: 'staff, employees, access, permissions',
        domain: 'users',
      },
    ],
  },
  {
    label: 'Settings',
    items: [
      {
        label: 'Settings',
        icon: 'settings',
        path: '/admin/settings',
        keywords: 'profile, backups, config',
        domain: 'settings',
      },
      {
        label: 'Global Config',
        icon: 'settings_suggest',
        path: '/admin/config',
        keywords: 'flags, variables, toggles',
        domain: 'settings',
      },
    ],
  },
];
