export const navSections = [
  {
    label: 'Home',
    items: [
      {
        label: 'Dashboard',
        icon: 'dashboard',
        path: '/admin',
        keywords: 'stats, home, sales, overview',
        domain: 'revenue',
      },
    ],
  },
  {
    label: 'Edit Website',
    items: [
      {
        label: 'Dynamic Layouts',
        icon: 'view_carousel',
        path: '/admin/layouts',
        keywords: 'layouts, sections, homepage',
        domain: 'settings',
      },
      {
        label: 'Edit Web Pages',
        icon: 'edit_note',
        path: '/admin/homepage',
        keywords: 'cms, homepage, hero, pages, policy',
        domain: 'settings',
      },
      {
        label: 'Photo Gallery',
        icon: 'photo_library',
        path: '/admin/gallery',
        keywords: 'photos, heritage, images',
        domain: 'settings',
      },
      {
        label: 'Policy Management',
        icon: 'gavel',
        path: '/admin/policies',
        keywords: 'policy, terms, legal, privacy',
        domain: 'settings',
      },
    ],
  },
  {
    label: 'Products & Stock',
    items: [
      {
        label: 'Categories',
        icon: 'category',
        path: '/admin/categories',
        keywords: 'taxonomy, tags, labels',
        domain: 'products',
      },
      {
        label: 'Product List',
        icon: 'inventory_2',
        path: '/admin/products',
        keywords: 'items, stock, catalog',
        domain: 'products',
      },
      {
        label: 'Stock Levels',
        icon: 'warehouse',
        path: '/admin/inventory',
        keywords: 'alerts, stock count, storage',
        domain: 'products',
      },
    ],
  },
  {
    label: 'Sales & Bookings',
    items: [
      {
        label: 'Purchase Orders',
        icon: 'shopping_bag',
        path: '/admin/orders',
        keywords: 'sales, checkout, delivery',
        domain: 'orders',
      },
      {
        label: 'Rental Orders',
        icon: 'inventory_2',
        path: '/admin/rentals',
        keywords: 'rentals, leases, returns',
        domain: 'orders',
      },
      {
        label: 'Custom Orders',
        icon: 'architecture',
        path: '/admin/custom-orders',
        keywords: 'customization, consultation, bespoke, custom orders',
        domain: 'orders',
      },
      {
        label: 'Customers',
        icon: 'group',
        path: '/admin/customers',
        keywords: 'users, crm, segments, vip',
        domain: 'users',
      },
      {
        label: 'Discount Coupons',
        icon: 'sell',
        path: '/admin/coupons',
        keywords: 'discounts, vouchers',
        domain: 'revenue',
      },
      {
        label: 'Payments',
        icon: 'payments',
        path: '/admin/payments',
        keywords: 'razorpay, cod, invoice, cashflow',
        domain: 'revenue',
      },
    ],
  },
  {
    label: 'Bookings & Feedback',
    items: [
      {
        label: 'Event Bookings',
        icon: 'event',
        path: '/admin/events',
        keywords: 'booking, setups, dates',
        domain: 'orders',
      },
      {
        label: 'Rental Calendar',
        icon: 'calendar_month',
        path: '/admin/rental-calendar',
        keywords: 'schedule, availability, tracking',
        domain: 'orders',
      },
    ],
  },
  {
    label: 'Reports & Settings',
    items: [
      {
        label: 'Sales Reports',
        icon: 'analytics',
        path: '/admin/analytics',
        keywords: 'trends, metrics, profits',
        domain: 'revenue',
      },
      {
        label: 'AI Engine Analytics',
        icon: 'psychology',
        path: '/admin/recommendations',
        keywords: 'recommendations, trending, metrics',
        domain: 'settings',
      },
      {
        label: 'Visual Search',
        icon: 'lens_blur',
        path: '/admin/visual-search',
        keywords: 'ai, lens, vision, image search',
        domain: 'settings',
      },
      {
        label: 'Marketing Emails',
        icon: 'campaign',
        path: '/admin/campaigns',
        keywords: 'marketing, email, newsletters',
        domain: 'revenue',
      },
      {
        label: 'Manage Staff',
        icon: 'groups',
        path: '/admin/team',
        keywords: 'staff, employees, access, permissions',
        domain: 'users',
      },
      {
        label: 'System Users',
        icon: 'admin_panel_settings',
        path: '/admin/system-users',
        keywords: 'admins, super, security, access',
        domain: 'users',
      },
      {
        label: 'Drafts Manager',
        icon: 'draft',
        path: '/admin/drafts',
        keywords: 'drafts, auto-save, unsaved, offline',
        domain: 'settings',
      },
      {
        label: 'Settings',
        icon: 'settings',
        path: '/admin/settings',
        keywords: 'profile, backups, config',
        domain: 'settings',
      },
      {
        label: 'Global Config',
        icon: 'settings_suggest',
        path: '/admin/config',
        keywords: 'flags, variables, toggles',
        domain: 'settings',
      },
    ],
  },
];
